name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master




jobs:

  - job: build_and_deploy_job
    displayName: Build and Deploy Job
    condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-black-dune-04a88301e-variable-group
    steps:
      - checkout: self
        submodules: true

      # Add Node.js setup with version 20.x
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"

      # Install Yarn
      - script: |
          npm install -g yarn
        displayName: "Install Yarn"

      # Install dependencies using Yarn
      - script: |
          yarn install
        displayName: "Install dependencies"

      - task: SonarCloudPrepare@3
        inputs:
          SonarQube: 'capexpipeline'
          organization: 'infralab'
          scannerMode: 'dotnet'
          dotnetScannerVersion: ''
          projectKey: 'InfraLab_Clean-Energy-CAPEX-Pipeline'
          projectName: 'Clean Energy CAPEX Pipeline'

      # Build the app using Yarn
      - script: |
          yarn build
        displayName: "Build application"


      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_DUNE_04A88301E)
          app_location: "/"
          api_location: ""
          output_location: "dist"

      - task: SonarCloudAnalyze@3
        inputs:
          jdkversion: 'JAVA_HOME_17_X64'